#FROM fuzzle/docker-nfs-server:latest
#ENV NFS_EXPORT_DIR_1=/nfs
#ENV NFS_EXPORT_DOMAIN_1=\*
#ENV NFS_EXPORT_OPTIONS_1=rw,insecure,no_subtree_check,no_root_squash,fsid=1

FROM cpuguy83/nfs-server:latest
