#!/usr/bin/env bash

#docker run -d --privileged --restart=always \
#-v /gut/data/nfs_share:/nfs \
#-p 111:111 -p 111:111/udp \
#-p 2049:2049 -p 2049:2049/udp \
#-p 32765:32765 -p 32765:32765/udp \
#-p 32766:32766 -p 32766:32766/udp \
#-p 32767:32767 -p 32767:32767/udp \
#nfs

docker run -d --name nfs_share --privileged -p 111 -p 2049 -v /gut/data/nfs_share:/data/nfs_share nfs /data/nfs_share

