FROM ubuntu:10.04

RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:happy-neko/ps3mediaserver && \
    apt-get update && apt-get install -y ps3mediaserver
